version: '3'

services:
  redis:
    image: redis
    networks:
      - deployml_network

  webserver:
    image: webserver
    build: ./webserver
    command: "uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - "80:80"
    networks:
      - deployml_network
    depends_on:
      - redis
    env_file:
      - app.env
networks:
  deployml_network: